### ISSUE TITLE
Britishmuseum liefert 502 - bad gateway

### ISSUE THREAD

**Issue by der-swing** [clmb/wikidata_workshop#5]
Das letzte Beispiel (Da Vincis Einträge aus dem Britischen Museum) aus dem Ordner "SPARQL2_Identifikatoren" liefert eine "bad gateway" Fehlermeldung.

Liegt sicher nicht am Code, sondern am Server vom Britischen Museum; vielleicht gibt es ein alternatives Beispiel, was man an die Stelle setzen kann?

**Comment by marisanest** [comment]
Hey @der-swing ,

danke für den Hinweis! 

Das Problem liegt tatsächlich beim Server des Britischen Museums. Wir haben eine neue Query geschrieben, die einen anderen SPARQL-Endpoint abfragt.

**Comment by clmb** [comment]
Thank you, @marisanest.
